version: '3.8'

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    volumes:
        - ./back:/usr/src/app
        - /usr/src/app/node_modules
    ports:
      - "3333:3333"
    depends_on:
      - database

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: dashboard
    volumes:
      - ./dashboard:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - /usr/src/app/.next/cache
    ports:
      - "3000:3000"

  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: linkup
      POSTGRES_PASSWORD: linkup
      POSTGRES_DB: linkup

  minio:
    image: 'minio/minio:latest'
    ports:
      - "6000:6000"
      - "8700:8700"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    volumes:
      - minio:/data/minio
    command: 'minio server /data/minio --console-address ":8700"'

networks:
  local_bridge:
    name: docker_network

volumes:
  psql-data:
  minio:
    driver: local
