version: "3.9"

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    depends_on:
      - database
    ports:
      - "3333:3333"
      - "9229:9229"
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: dashboard
    volumes:
      - ./dashboard:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - /usr/src/app/.next/cache
    ports:
      - "3000:3000"

  database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: linkup
      POSTGRES_PASSWORD: linkup
      POSTGRES_DB: linkup

networks:
  local_bridge:
    name: docker_network
    driver: bridge
    attachable: false

volumes:
  psql-data:
    driver: local
